### ISSUE TITLE
During Bundling: Error: react-router-dom/NavLink.js: Line 48: Invalid regular expression

### ISSUE THREAD

**Issue by dschinkel** [deepak1556/gulp-browserify#101]
Not sure if this is a react-router issue or gulp-browserify issue. I've posted this issue in both repose. 

Had always run `"gulp-browserify": "^0.5.1"` and it was fine for 3 years.

All I know is all of a sudden, I get this error when this has been file for a long time now as it was.  I hadn't upgraded gulp-browserify nor react-router and it was fine up till now and no idea why it's complaining:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: Parsing file /Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/react-router-dom/NavLink.js: Line 48: Invalid regular expression
    at Deps.parseDeps (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/node_modules/module-deps/index.js:339:28)
    at /Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/node_modules/module-deps/index.js:282:29
    at ConcatStream.<anonymous> (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:194:15)
    at ConcatStream.EventEmitter.emit (domain.js:441:20)
    at finishMaybe (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at Object.onceWrapper (events.js:277:13)
Emitted 'error' event at:
    at Transform.onerror (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:189:13)
    at Transform.EventEmitter.emit (domain.js:441:20)
    at Stream.<anonymous> (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/index.js:123:14)
    at Stream.<anonymous> (/Users/coffeegrinds/Desktop/we-do-tdd-current-config/node_modules/gulp-browserify/node_modules/browserify/index.js:344:22)
    at Stream.emit (events.js:194:15)
    at Stream.EventEmitter.emit (domain.js:441:20)
    at Transform.emit (events.js:194:15)
    at Transform.EventEmitter.emit (domain.js:441:20)
    at Deps.emit (events.js:189:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by dschinkel** [comment]
Fixed, I had an issue in my gulp transpile script.

Changed:

```
gulp.task('transpile', function () {
  return gulp.src(['./src/**/*.js', '!./src/client/less/*.js'])
    .pipe(babel())
    .pipe(gulp.dest("build"));
});

```
To:

```
gulp.task('transpile', function () {
  gulp.src(['./src/**/*.js', '!./src/client/less/*.js'])
    .pipe(babel())
    .pipe(gulp.dest("build"));
});
```
